### ISSUE TITLE
Any chance of adding 10.14 support?

### ISSUE THREAD

**Issue by mikemcduffie** [samuelmeuli/glance#1]
Looks like a nice plugin but not worth "upgrading" to Catalina for it.

**Comment by samuelmeuli** [comment]
Thanks, @mikemcduffie! Glance uses the [new Quick Look API](https://developer.apple.com/documentation/quartz/qlpreviewingcontroller/2867936-preparepreviewoffile) that was introduced in 10.15, so it unfortunately won't work with earlier versions of macOS.
