### ISSUE TITLE
Crash when previewing ZIP with single file entry

### ISSUE THREAD

**Issue by fregante** [samuelmeuli/glance#10]
Document: [index.js.zip](https://github.com/samuelmeuli/glance/files/4640456/index.js.zip) (created via macOS’ own File → Compress)

<img width="707" alt="" src="https://user-images.githubusercontent.com/1402241/82152295-724aab80-9860-11ea-92f3-32df77789133.png">

I only have `Video.qlgenerator` and `WebpQuickLook.qlgenerator` in `~/Library/QuickLook` installed via Brew

macOS 10.15.4

I already turned it off and on again (the computer)

**Comment by fregante** [comment]
I do have BetterZip installed (via Brew), which is what handles it normally, but even if I completely removed it and [refresh + restart](https://apple.stackexchange.com/a/260140) QuickLook, Glance still fails.

**Comment by samuelmeuli** [comment]
Probably an issue with my `zipinfo` regex. 

```
Zip file size: 844 bytes, number of entries: 1
-rw-r--r--  2.0 unx     1346 bX defN 20-May-05 01:37 index.js
1 file, 1346 bytes uncompressed, 650 bytes compressed:  51.7%
```

The regex expects `files` instead of `file` on the last line.
