### ISSUE TITLE
Binary releases and Homebrew Cask

### ISSUE THREAD

**Issue by crunchtime-ali** [samuelmeuli/glance#11]
Dear Samuel,

it's very good to distribute Glance via App Store but some people might prefer installing binary releases themself or via Homebrew Cask.
Can you supply Binaries for Glance for every GitHub release?

If you do I will take care of having it added to Homebrew.

Some people also might not be able to install Glance because of restrictions on their work devices like this:

<img width="415" alt="CleanShot 2020-05-18 at 00 29 55@2x" src="https://user-images.githubusercontent.com/7140800/82161633-b9579180-989e-11ea-9a5f-c1018e63c926.png">

**Comment by samuelmeuli** [comment]
Done: [v1.0.0](https://github.com/samuelmeuli/glance/releases/tag/v1.0.0)

If you could manage the formula, that would be great 😊

Paths for the zap stanza:

- `~/Library/Application\ Scripts/com.samuelmeuli.Glance/`
- `~/Library/Application\ Scripts/com.samuelmeuli.Glance.QLPlugin/`
- `~/Library/Containers/com.samuelmeuli.Glance/`
- `~/Library/Containers/com.samuelmeuli.Glance.QLPlugin/`
- `~/Library/Group\ Containers/group.com.samuelmeuli.glance/`

**Comment by crunchtime-ali** [comment]
@samuelmeuli Thank you very much. I will take care of the formula later today and report here.

**Comment by crunchtime-ali** [comment]
@samuelmeuli I am placing the `Glance.app` in `/Applications/` and executing it but that doesn't seem to be enough. Will I have to copy the stanzas in the appropriate folders myself or how is that done?

**Comment by samuelmeuli** [comment]
That should be enough. The Quick Look plugin is registered when the app is opened for the first time.

Are you on macOS 10.15?

**Comment by crunchtime-ali** [comment]
@samuelmeuli You can try the cask yourself when you create it with `brew cask create glance`, then replace the template with this:

```
cask 'glance' do
  version '1.0.0'
  sha256 '8ef7ba4a5130955e213fdfcc2bf43cba47c742d5f02e0e9c62405acaf19626b5'

  url "https://github.com/samuelmeuli/glance/releases/download/v#{version}/Glance.dmg"
  appcast 'https://github.com/samuelmeuli/glance/releases.atom'
  name 'Glance'
  homepage 'https://github.com/samuelmeuli/glance'
  depends_on macos: '>= :catalina'

  app 'Glance.app'
  installer script: {
    executable: "Glance.app/Contents/MacOS/Glance",
  }

  zap trash: [
    '~/Library/Application\ Scripts/com.samuelmeuli.Glance/',
    '~/Library/Application\ Scripts/com.samuelmeuli.Glance.QLPlugin/',
    '~/Library/Containers/com.samuelmeuli.Glance/',
    '~/Library/Containers/com.samuelmeuli.Glance.QLPlugin/',
    '~/Library/Group\ Containers/group.com.samuelmeuli.glance/',
  ]
end
```

then `brew cask install glance`.

**Comment by samuelmeuli** [comment]
```
installer script: {
  executable: "Glance.app/Contents/MacOS/Glance",
}
```

This part is breaking the installation for me. Without it it's working fine.

I suspect this is because when the app is opened by the script, it's not yet in the `/Applications/` directory. And this seems to be a requirement for Quick Look plugins to be registered by macOS.

**Comment by crunchtime-ali** [comment]
@samuelmeuli Thank you for trying. I made some progress. I moved the execution of Glance.app to postflight section. It now executes the app but the terminal output hangs at the following until you quit the app manually. After quitting it Glance is working as expected.
Now I could set a small timer and quit the application in the postflight script but I think the cleaner way would be to set a `--setup` or `--quiet` argument when calling the binary, then you do the setup magic, then the app quits with return code zero by itself, preferably without showing a dock icon.  How do you think about it?

This is where the cask installation hangs:

```
==> Installing Cask glance
==> Moving App 'Glance.app' to '/Applications/Glance.app'.
```

**Comment by samuelmeuli** [comment]
I think the user should open the app by themselves. Automatically executing a binary that was downloaded from the internet seems a bit problematic to me. Maybe a note in `caveats` is enough?

**Comment by crunchtime-ali** [comment]
@samuelmeuli My opinion differs a bit but I respect yours and therefore added it to the `caveats` and created a merge request. Since it seems to be the first QL-plugin of its kind to enter the Caskroom I suspect there will be some discussion so feel free to chime in at https://github.com/Homebrew/homebrew-cask/pull/82816

**Comment by samuelmeuli** [comment]
Great, I'm curious to hear what other people think. Thanks a lot for working on this, @crunchtime-ali! 😊

**Comment by crunchtime-ali** [comment]
@samuelmeuli Can you maybe chime in on vitorgalvaos' question https://github.com/Homebrew/homebrew-cask/pull/82816#discussion_r426924354?
I looked at the source code but feel you are more qualified to answer the question. As I understand it the Quick Look plugin resides in `/Applications/Glance.app/Contents/PlugIns/QLPlugin.appex`

**Comment by samuelmeuli** [comment]
Glance is now available on Homebrew! 🎉

```sh
brew cask install glance
```

Many thanks to @crunchtime-ali!
