### ISSUE TITLE
Choose which file types previewed with Glance

### ISSUE THREAD

**Issue by axelburks** [samuelmeuli/glance#15]
I prefer to preview zip file with BetterZip, because it's my main archiver manager. So I think maybe it's more friendly to give options to user to select with types associated with Glance.

**Comment by samuelmeuli** [comment]
Glance's UTI list is [static](https://github.com/samuelmeuli/glance/blob/15d6fd6cec9b1cf2411bc1166162dda2cd8c78cc/QLPlugin/Info.plist#L29), this isn't something I can make configurable in the app.

If you go to System Preferences → Extensions → Quick Look, you can rearrange your plugins. Maybe this allows you to specify which plugin should be given priority?
