### ISSUE TITLE
Support for Sequel Pro files

### ISSUE THREAD

**Issue by JvSomeren** [samuelmeuli/glance#19]
The output of `mdls` on my system is as follows:
```
kMDItemContentType     = "com.sequelpro.sequelpro.sql"
kMDItemContentTypeTree = (
    "com.sequelpro.sequelpro.sql",
    "public.plain-text",
    "public.text",
    "public.data",
    "public.item",
    "public.content"
)
```

Would it be possible to support this?

**Comment by samuelmeuli** [comment]
Sure! I found [a few more UTIs](https://github.com/sequelpro/sequelpro/blob/f0987c5354dcadf4a13aa5595504977b157158a0/Resources/Plists/Info.plist#L270-L378) in Sequel Pro's repository. Besides `com.sequelpro.SequelPro.sql`, two others implement `public.plain-text`, so it should be possible to generate previews for them:

- `com.sequelpro.SequelPro.spf`
- `com.sequelpro.SequelPro.spTheme`

Would you be able to find out what kind of data is stored these files so we can apply syntax highlighting to them?

**Comment by JvSomeren** [comment]
I would be happy to help! Just not quite sure what you are referring to with "kind of data". These .sql-files are just regular SQL dumps in my case, so probably just plaintext?
It's just my OS associates these files with Sequel Pro.

**Comment by samuelmeuli** [comment]
I'm wondering what kind of information is stored in `spf` and `spTheme` files, so I can specify the correct language for syntax highlighting. [`spTheme` seems to be XML](https://github.com/rainglow/sequel-pro/blob/master/themes/Bold%20(rainglow).spTheme). I couldn't find an example for `spf` yet, would you mind trying to generate one and seeing what's in it?

**Comment by JvSomeren** [comment]
Aha! I was able to export a [`.spf`-file](https://gist.github.com/JvSomeren/d6c2c6133e559d7f2f90009d4fe1452f), just like `spTheme` it's XML. Hope this helps :)

**Comment by samuelmeuli** [comment]
Added, thanks!

**Comment by JvSomeren** [comment]
Awesome! Thank you too!
