### ISSUE TITLE
Markdown is not rendered

### ISSUE THREAD

**Issue by karkraeg** [samuelmeuli/glance#2]
Hi, I installed Glance via the AppStore, Sourcecode files are working fine but Markdown isnt:

<img width="1078" alt="2020-05-16_214425@2x" src="https://user-images.githubusercontent.com/8436596/82128836-7e7e2c80-97be-11ea-8f0a-1ff5aaffe10d.png">

FWIW I had [qlmarkdown](https://github.com/toland/qlmarkdown) installed before, but I did uninstall vom /Library/QuickLook and the User Library and ran `qlmanage -r cache && qlmanage -r`, restarted and so on, still no Markdown Preview.

**Comment by samuelmeuli** [comment]
Thanks for reporting the issue!

Apparently, the `net.daringfireball.markdown` UTI isn't available by default. Adding the dynamic UTIs of Markdown file extensions should hopefully fix this.

**Comment by samuelmeuli** [comment]
Please let me know if the next release doesn't fix this :)

**Comment by Stramon1um** [comment]
Hi, I just installed the new release and still I have the same issue with .md files whereas for the rest is super fine (i'm the one that posted it on reddit)

**Comment by samuelmeuli** [comment]
Continued in #17
