### ISSUE TITLE
Loads remote images in Markdown

### ISSUE THREAD

**Issue by fregante** [samuelmeuli/glance#9]
The readme states:

> **Why are images in my Markdown files not loading?**
> 
> Glance only has access to the file that’s being previewed (`com.apple.security.files.user-selected.read-only` entitlement). Any image files referenced from Markdown are therefore not loaded.

But these images are [loaded from a remote server](https://github.com/fregante/webext-base-css/blame/5e49453e04d8b97eee3fed983877a773b0df7b76/readme.md#L14)

<img width="918" alt="" src="https://user-images.githubusercontent.com/1402241/82151883-2860c600-985e-11ea-9dba-fd1a2807b16a.png">

**Comment by samuelmeuli** [comment]
Thanks for reporting! I've already fixed this: https://github.com/samuelmeuli/glance/commit/645c7d1891c11b1f6b63feee54c27c31ddbc6894.

I'm about to submit to the App Store, so you should hopefully get the fix tomorrow :)

**Comment by samuelmeuli** [comment]
It might be worth discussing whether remote assets should selectively be allowed. For now it's offline assets only though.

**Comment by fregante** [comment]
I'm happy to hear that! Off by default sounds good.

**Comment by samuelmeuli** [comment]
Released in [v1.1.0](https://github.com/samuelmeuli/glance/releases/tag/v1.1.0).
